const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
.get('/therapy', (req, res) => res.render('pages/therapy'))
  .get('/supervision', (req, res) => res.render('pages/supervision'))
.get('/parent-consultations', (req, res) => res.render('pages/parent-consultations'))
.get('/emdr', (req, res) => res.render('pages/emdr'))
.get('/cbt', (req, res) => res.render('pages/cbt'))
.get('/act', (req, res) => res.render('pages/act'))
.get('/contact', (req, res) => res.render('pages/contact'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
